spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Socials
    username: project_user
    password: project
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect